main: team.bukkitserverforbukkitpeople.Main
name: CommunityPlugin
version: 1.0

commands:
  something:
    description: Tells you if you are a player or not
  tp:
    description: Basic teleport commands
  pvpopt:
    description: Opt in or out of pvp